id: P885D54CD
initial_creation_type: ocr
source_metadata:
  volumes:
    fb8c2ca284204515b1a68234a70d25ee:
      base_file: v012.txt
      image_group_id: I1PD95857
      title: དཔལ་རྡོ་རྗེ་རྣལ་འབྱོར་མའི་སྒྲུབ་ཐབས།
      total_pages: 1544
      volume_number: 12
